---
title: "Ethan S. Young, Ph.D."
description: "Curriculum Vitae"
author: Ethan Young
tocbot: true
---

```{r setup,echo=F,message=F,warning=F}
# Libraries
library(tidyverse)
library(htmltools)
library(googlesheets)
library(glue)

# Publications
journals <- c("Journal of Personality and Social Psychology",
              "Self and Identity",
              "Psychological Science",
              "Evolutionary Behavioral Sciences",
              "Developmental Psychology",
              "Attachment and Human Development",
              "Trends in Cognitive Sciences")

# Get pubs gsheet
gs_auth()
pubs <- gs_read(gs_title("cv-data"),ws = 1) %>% 
  mutate(citation = str_replace(citation,"Young, E. S.","<b>Young, E. S.</b>"))
positions <- gs_read(gs_title("cv-data"), ws = 2)
education <- gs_read(gs_title("cv-data"), ws = 3)
awards <- gs_read(gs_title("cv-data"), ws = 4)
teaching <- gs_read(gs_title("cv-data"), ws = 5)

walk(journals, function(x){
  pubs <<- pubs %>% 
    mutate(citation = ifelse(str_detect(citation,x), str_replace(citation,x,paste0("<em>",x,"</em>")),citation))
})

# Journal articles
articles <- pubs %>% 
  filter(pub_type=="journal") %>% 
  arrange(desc(year)) %>% 
  mutate(count = 1:n()) %>% 
  group_by(year) %>%
  mutate(count_year = 1:n(),
         count_auth = ifelse(str_detect(citation,"^<b>Young, E. S."), count*-1, count_year),
         border     = ifelse(count_year == max(count_auth) | n()==1,"solid","none"),
         year_group = ifelse(count_auth == min(count_auth),year,"") %>% str_replace("-"," ")) %>% 
  arrange(desc(year),count_auth) %>% 
  ungroup() %>% 
  mutate(
    border   = ifelse(count == last(count),"",border),
    download = ifelse(is.na(download),"", 
                      paste0("<a class = 'label success' role = 'button' target = '_blank' href =", download, ">Download</a>")),
    abstract = ifelse(is.na(abstract),"", 
                      paste0("<a class = 'label focus collapse-toggle'",
                             "href = '#abstract-",year,"-",count,"' ",
                             "role = 'button'>Abstract<span class = 'caret down'></span></a> ",
                             ifelse(is.na(download)," ",download),
                             "<div id = 'abstract","-",year,"-",count,"' ",
                             "class = 'collapse-box hide bg-aluminum', ",
                             "style = 'margin: 0; padding: 25px;'>",
                             "<p class = 'small'><em>", abstract, "</em></p></div>",
                             "</div>"))
  ) 

# Chapters
chapters <- pubs %>% 
  filter(pub_type=="chapter") %>% 
  arrange(desc(year)) %>% 
  mutate(count = 1:n()) %>% 
  group_by(year) %>%
  mutate(count_year = 1:n(),
         count_auth = ifelse(str_detect(citation,"^<b>Young, E. S."), count*-1, count_year),
         border     = ifelse(count_year == max(count_auth) | n()==1,"solid","none"),
         year_group = ifelse(count_auth == min(count_auth),year,"") %>% str_replace("-"," ")) %>% 
  arrange(desc(year),count_auth) %>% 
  ungroup() %>% 
  mutate(
    border   = ifelse(count == last(count),"",border),
    download = ifelse(is.na(download),"", 
                      paste0("<a class = 'label success' role = 'button' target = '_blank' href =", download, ">Download</a>")),
    abstract = ifelse(is.na(abstract),"", 
                      paste0("<a class = 'label focus collapse-toggle'",
                             "href = '#abstract-",year,"-",count,"' ",
                             "role = 'button'>Abstract<span class = 'caret down'></span></a> ",
                             ifelse(is.na(download)," ",download),
                             "<div id = 'abstract","-",year,"-",count,"' ",
                             "class = 'collapse-box hide bg-aluminum', ",
                             "style = 'margin: 0; padding: 25px;'>",
                             "<p class = 'small'><em>", abstract, "</em></p></div>",
                             "</div>"))
  )

# In Progress
in_progress <- pubs %>% 
  filter(pub_type %in% c("invited","under review")) %>% 
  mutate(count = 1:n()) %>% 
  group_by(pub_type) %>%
  mutate(count_year = 1:n(),
         count_auth = ifelse(str_detect(citation,"^<b>Young, E. S."), count*-1, count_year),
         border     = ifelse(count_year == max(count_auth) | n()==1,"solid","none"),
         year_group = ifelse(count_auth == min(count_auth),pub_type,"") %>% str_replace("-"," ")) %>% 
  arrange(pub_type,count_auth) %>%
  ungroup() %>% 
  mutate(
    border   = ifelse(count == last(count),"",border),
    download = ifelse(is.na(download),"", 
                      paste0("<a class = 'label success' role = 'button' target = '_blank' href =", download, ">Download</a>")),
    abstract = ifelse(is.na(abstract),"", 
                      paste0("<a class = 'label focus collapse-toggle'",
                             "href = '#abstract-",year,"-",count,"' ",
                             "role = 'button'>Abstract<span class = 'caret down'></span></a> ",
                             ifelse(is.na(download)," ",download),
                             "<div id = 'abstract","-",year,"-",count,"' ",
                             "class = 'collapse-box hide bg-aluminum', ",
                             "style = 'margin: 0; padding: 25px;'>",
                             "<p class = 'small'><em>", abstract, "</em></p></div>",
                             "</div>"))
  )

# Talks
talks <- pubs %>% 
  filter(pub_type=="presentation") %>% 
  arrange(desc(year)) %>% 
  mutate(count = 1:n()) %>% 
  group_by(year) %>%
  mutate(count_year = 1:n(),
         count_auth = ifelse(str_detect(citation,"^<b>Young, E. S."), count*-1, count_year),
         border     = ifelse(count_year == max(count_auth) | n()==1,"solid","none"),
         year_group = ifelse(count_auth == min(count_auth),year,"") %>% str_replace("-"," ")) %>% 
  arrange(desc(year),count_auth) %>% 
  ungroup() %>% 
  mutate(
    border   = ifelse(count == last(count),"",border),
    download = ifelse(is.na(download),"", 
                      paste0("<a class = 'label success' role = 'button' target = '_blank' href =", download, ">Download</a>")),
    abstract = ifelse(is.na(abstract),"", 
                      paste0("<a class = 'label focus collapse-toggle'",
                             "href = '#abstract-",year,"-",count,"' ",
                             "role = 'button'>Abstract<span class = 'caret down'></span></a> ",
                             ifelse(is.na(download)," ",download),
                             "<div id = 'abstract","-",year,"-",count,"' ",
                             "class = 'collapse-box hide bg-aluminum', ",
                             "style = 'margin: 0; padding: 25px;'>",
                             "<p class = 'small'><em>", abstract, "</em></p></div>",
                             "</div>"))
  )

# Posters
posters <- pubs %>% 
  filter(pub_type=="poster") %>% 
  arrange(desc(year)) %>% 
  mutate(count = 1:n()) %>% 
  group_by(year) %>%
  mutate(count_year = 1:n(),
         #count_auth = ifelse(str_detect(citation,"^<b>Young, E. S."), count*-1, count_year),
         border     = ifelse(count_year == max(count_year) | n()==1,"solid","none"),
         year_group = ifelse(count_year == min(count_year),year,"") %>% str_replace("-"," ")) %>% 
  arrange(desc(year)) %>% 
  ungroup() %>% 
  mutate(
    border   = ifelse(count == last(count),"",border),
    download = ifelse(is.na(download),"", 
                      paste0("<a class = 'label success' role = 'button' target = '_blank' href =", download, ">Download</a>")),
    abstract = ifelse(is.na(abstract),"", 
                      paste0("<a class = 'label focus collapse-toggle'",
                             "href = '#abstract-",year,"-",count,"' ",
                             "role = 'button'>Abstract<span class = 'caret down'></span></a> ",
                             ifelse(is.na(download)," ",download),
                             "<div id = 'abstract","-",year,"-",count,"' ",
                             "class = 'collapse-box hide bg-aluminum', ",
                             "style = 'margin: 0; padding: 25px;'>",
                             "<p class = 'small'><em>", abstract, "</em></p></div>",
                             "</div>"))
  )
```

### Employment

```{r academic_positions,echo=F,message=F,warning=F}
tags$fieldset(
  tags$legend(style = "font-size: 16px;","Academic Positions"),
  tags$table(
    style = "margin: 0;",
    HTML(
      positions %>% 
        mutate(last_row = ifelse(row_number()== max(row_number()), "none","solid")) %>% 
        glue_data(
          "<tr>",
          "<td class = 'w15' style = '",
          "border-style: none none {last_row} none;",
          "border-width: 1px 1px 1px 1px;",
          "border-color: rgba(0,0,0,.05);'>",
          "<b>{start}-{end}</b>",
          "</td>",
          "<td style = '",
          "border-style: none none {last_row} none;",
          "border-width: 1px 1px 1px 1px;",
          "border-color: rgba(0,0,0,.05);'>",
          "{position}<br>{institution}<br>{people}",
          "</td>",
          "</tr>"
        ) %>% 
        paste(collapse = "")
    )
  )
)
```

### Education

```{r edu,echo=F,message=F,warning=F}
tags$fieldset(
  tags$legend(style = "font-size: 16px;","Graduate"),
  tags$table(
    style = "margin: 0;",
    HTML(
      education %>% 
        filter(type == "graduate") %>% 
        arrange(desc(end)) %>% 
        mutate(last_row = ifelse(row_number()== max(row_number()), "none","solid")) %>% 
        glue_data(
          "<tr>",
          "<td class = 'w15' style = '",
          "border-style: none none {last_row} none;",
          "border-width: 1px 1px 1px 1px;",
          "border-color: rgba(0,0,0,.05);'>",
          "<b>{start}-{end}</b>",
          "</td>",
          "<td style = '",
          "border-style: none none {last_row} none;",
          "border-width: 1px 1px 1px 1px;",
          "border-color: rgba(0,0,0,.05);'>",
          "{degree}<br>{institution}<br>{subject}",
          "</td>",
          "</tr>"
        ) %>% 
        paste(collapse = "")
    )
  )
)

tags$fieldset(
  tags$legend(style = "font-size: 16px;","Undergraduate"),
  tags$table(
    style = "margin: 0;",
    HTML(
      education %>% 
        filter(type == "undergraduate") %>% 
        arrange(desc(end)) %>% 
        mutate(last_row = ifelse(row_number()== max(row_number()), "none","solid")) %>% 
        glue_data(
          "<tr>",
          "<td class = 'w15' style = '",
          "border-style: none none {last_row} none;",
          "border-width: 1px 1px 1px 1px;",
          "border-color: rgba(0,0,0,.05);'>",
          "<b>{start}-{end}</b>",
          "</td>",
          "<td style = '",
          "border-style: none none {last_row} none;",
          "border-width: 1px 1px 1px 1px;",
          "border-color: rgba(0,0,0,.05);'>",
          "{degree}<br>{institution}<br>{subject}",
          "</td>",
          "</tr>"
        ) %>% 
        paste(collapse = "")
    )
  )
)
```

### Honors & Awards

```{r fellowships,echo=F,message=F,warning=F}
tags$fieldset(
  tags$legend(style = "font-size: 16px;","Fellowships"),
  tags$table(
    style = "margin: 0;",
    HTML(
      awards %>% 
        arrange(desc(end)) %>% 
        mutate(last_row = ifelse(row_number()== max(row_number()), "none","solid")) %>% 
        glue_data(
          "<tr>",
          "<td class = 'w15' style = '",
          "border-style: none none {last_row} none;",
          "border-width: 1px 1px 1px 1px;",
          "border-color: rgba(0,0,0,.05);'>",
          "<b>{start}-{end}</b>",
          "</td>",
          "<td style = '",
          "border-style: none none {last_row} none;",
          "border-width: 1px 1px 1px 1px;",
          "border-color: rgba(0,0,0,.05);'>",
          "{award}<br>{institution}",
          "</td>",
          "</tr>"
        ) %>% 
        paste(collapse = "")
    )
  )
)
```

### Publications

```{r peer_reviewed,echo=F,message=F,warning=F}
tags$fieldset(
  tags$legend(style = "font-size: 16px;","Peer Reviewed Articles"),
  tags$table(style = "margin: 0;",
             tags$tbody(
               tags$table(
                 HTML(
                   articles %>% 
                     str_glue_data(
                       "<tr >",
                       "<td class = 'w15' style = '",
                       "border-style: none none {border} none;",
                       "border-width: 1px 1px 1px 1px;",
                       "border-color: rgba(0,0,0,.05);'>",
                       "<b>{year_group}</b>",
                       "</td>",
                       "<td style = '",
                       "border-style: none none {border} none;",
                       "border-width: 1px 1px 1px 1px;",
                       "border-color: rgba(0,0,0,.05);'>",
                       "<ul><li>{citation}</li>",
                       "<div data-component = 'collapse'>",
                       "{abstract}",
                       "</div>",
                       "</ul>",
                       "</td>",
                       "</tr>"
                     ) %>% 
                     paste(collapse = "")
                 )
               )
             )
  )
)
```

```{r chapters,echo=F,message=F,warning=F}
tags$fieldset(
  tags$legend(style = "font-size: 16px;","Book Chapters"),
  tags$table(style = "margin: 0;",
             tags$tbody(
               tags$table(
                 HTML(
                   chapters %>% 
                     str_glue_data(
                       "<tr >",
                       "<td class = 'w15' style = '",
                       "border-style: none none {border} none;",
                       "border-width: 1px 1px 1px 1px;",
                       "border-color: rgba(0,0,0,.05);'>",
                       "<b>{year_group}</b>",
                       "</td>",
                       "<td style = '",
                       "border-style: none none {border} none;",
                       "border-width: 1px 1px 1px 1px;",
                       "border-color: rgba(0,0,0,.05);'>",
                       "<ul><li>{citation}</li>",
                       "<div data-component = 'collapse'>",
                       "{download}",
                       "</div>",
                       "</ul>",
                       "</td>",
                       "</tr>"
                     ) %>% 
                     paste(collapse = "")
                 )
               )
             )
  )
)
```

```{r working,echo=F,message=F,warning=F}
tags$fieldset(
  tags$legend(style = "font-size: 16px;","In Progress"),
  tags$table(style = "margin: 0;",
             tags$tbody(
               tags$table(
                 HTML(
                   in_progress %>% 
                     str_glue_data(
                       "<tr >",
                       "<td class = 'w15' style = '",
                       "border-style: none none {border} none;",
                       "border-width: 1px 1px 1px 1px;",
                       "border-color: rgba(0,0,0,.05);'>",
                       "<b>{year_group}</b>",
                       "</td>",
                       "<td style = '",
                       "border-style: none none {border} none;",
                       "border-width: 1px 1px 1px 1px;",
                       "border-color: rgba(0,0,0,.05);'>",
                       "<ul><li>{citation}</li>",
                       "<div data-component = 'collapse'>",
                       "{download}",
                       "</div>",
                       "</ul>",
                       "</td>",
                       "</tr>"
                     ) %>% 
                     paste(collapse = "")
                 )
               )
             )
  )
)
```

### Presentations

```{r talks,echo=F,message=F,warning=F}
tags$fieldset(
  tags$legend(style = "font-size: 16px;","Talks"),
  tags$table(style = "margin: 0;",
             tags$tbody(
               tags$table(
                 HTML(
                   talks %>% 
                     str_glue_data(
                       "<tr >",
                       "<td class = 'w15' style = '",
                       "border-style: none none {border} none;",
                       "border-width: 1px 1px 1px 1px;",
                       "border-color: rgba(0,0,0,.05);'>",
                       "<b>{year_group}</b>",
                       "</td>",
                       "<td style = '",
                       "border-style: none none {border} none;",
                       "border-width: 1px 1px 1px 1px;",
                       "border-color: rgba(0,0,0,.05);'>",
                       "<ul><li>{citation}</li>",
                       "<div data-component = 'collapse'>",
                       "{download}",
                       "</div>",
                       "</ul>",
                       "</td>",
                       "</tr>"
                     ) %>% 
                     paste(collapse = "")
                 )
               )
             )
  )
)
```

```{r posters,echo=F,message=F,warning=F}
tags$fieldset(
  tags$legend(style = "font-size: 16px;","Posters"),
  tags$table(style = "margin: 0;",
             tags$tbody(
               tags$table(
                 HTML(
                   posters %>% 
                     str_glue_data(
                       "<tr >",
                       "<tr >",
                       "<td class = 'w15' style = '",
                       "border-style: none none {border} none;",
                       "border-width: 1px 1px 1px 1px;",
                       "border-color: rgba(0,0,0,.05);'>",
                       "<b>{year_group}</b>",
                       "</td>",
                       "<td style = '",
                       "border-style: none none {border} none;",
                       "border-width: 1px 1px 1px 1px;",
                       "border-color: rgba(0,0,0,.05);'>",
                       "<ul><li>{citation}</li>",
                       "<div data-component = 'collapse'>",
                       "{download}",
                       "</div>",
                       "</ul>",
                       "</td>",
                       "</tr>"
                     ) %>% 
                     paste(collapse = "")
                 )
               )
             )
  )
)
```

### Teaching

```{r teaching, echo=F, message=F, warning=F}
tags$fieldset(
  tags$legend(style = "font-size: 16px;","Instructor"),
  tags$table(
    style = "margin: 0;",
    HTML(
      teaching %>% 
        filter(position == "Instructor") %>% 
        mutate(last_row = ifelse(row_number()== max(row_number()), "none","solid")) %>% 
        glue_data(
          "<tr>",
          "<td class = 'w15' style = '",
          "border-style: none none {last_row} none;",
          "border-width: 1px 1px 1px 1px;",
          "border-color: rgba(0,0,0,.05);'>",
          "<b>{semester} {year}</b>",
          "</td>",
          "<td style = '",
          "border-style: none none {last_row} none;",
          "border-width: 1px 1px 1px 1px;",
          "border-color: rgba(0,0,0,.05);'>",
          "{title} ({course})<br>{institution}",
          "</td>",
          "</tr>"
        ) %>% 
        paste(collapse = "")
    )
  )
)

tags$fieldset(
  tags$legend(style = "font-size: 16px;","Section Leader"),
  tags$table(
    style = "margin: 0;",
    HTML(
      teaching %>% 
        filter(position == "Section Leader") %>% 
        mutate(last_row = ifelse(row_number()== max(row_number()), "none","solid")) %>% 
        glue_data(
          "<tr>",
          "<td class = 'w15' style = '",
          "border-style: none none {last_row} none;",
          "border-width: 1px 1px 1px 1px;",
          "border-color: rgba(0,0,0,.05);'>",
          "<b>{semester} {year}</b>",
          "</td>",
          "<td style = '",
          "border-style: none none {last_row} none;",
          "border-width: 1px 1px 1px 1px;",
          "border-color: rgba(0,0,0,.05);'>",
          "{title} ({course})<br>{institution}",
          "</td>",
          "</tr>"
        ) %>% 
        paste(collapse = "")
    )
  )
)

tags$fieldset(
  tags$legend(style = "font-size: 16px;","Teaching Assistant"),
  tags$table(
    style = "margin: 0;",
    HTML(
      teaching %>% 
        filter(position == "Teaching Assistant") %>% 
        mutate(last_row = ifelse(row_number()== max(row_number()), "none","solid")) %>% 
        glue_data(
          "<tr>",
          "<td class = 'w15' style = '",
          "border-style: none none {last_row} none;",
          "border-width: 1px 1px 1px 1px;",
          "border-color: rgba(0,0,0,.05);'>",
          "<b>{semester} {year}</b>",
          "</td>",
          "<td style = '",
          "border-style: none none {last_row} none;",
          "border-width: 1px 1px 1px 1px;",
          "border-color: rgba(0,0,0,.05);'>",
          "{title} ({course})<br>{institution}",
          "</td>",
          "</tr>"
        ) %>% 
        paste(collapse = "")
    )
  )
)
```

